name: cicd

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ '1.20', '1.21' ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: |
          make tests

  release:
    runs-on: ubuntu-latest
    needs:
      - build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    strategy:
      matrix:
        go-version: [ '1.20', '1.21' ]

    steps:
      - name: Create Release
        run: |
          # Replace this with your actual release creation script
          echo "Creating release for version ${{ matrix.go-version }}"
