name: Manual Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag_version_message:
        description: 'Enter a description'
        required: true
        type: string
      release_type:
        description: 'Select the release type'
        type: choice
        required: true
        default: 'patch'
        options:
          - major
          - minor
          - patch

jobs:

  #releaser:
  #  permissions:
  #    id-token: write # To sign the provenance.
  #    contents: write # To upload assets to release.
  #    actions: read # To read the workflow path.
  #  needs: create-tag
  #  uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.8.0
  #  with:
  #    go-version: 1.21
  #    config-file: .slsa-goreleaser.yml
  #    evaluated-envs: "VERSION:${{needs.create-tag.outputs.NEW_VERSION}}"
  #    upload-assets: true
  #    upload-tag-name: ${{ needs.create-tag.outputs.NEW_VERSION }}

  create-tag:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    outputs:
      latest_tag: steps.set-tag.outputs.LATEST_TAG
      new_version: steps.create-version.outputs.NEW_VERSION

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get latest tag
        id: set-tag
        env:
          LATEST_TAG: ${{ needs.set-tag.outputs.latest_tag }}
        run: |
          git fetch --tags
          latest_tag=$(git tag --sort=-creatordate | head -n 1)
          echo "my: "${latest_tag}
          echo "LATEST_TAG=${latest_tag}" >> $GITHUB_OUTPUT
          echo "my2: "${{ env.LATEST_TAG }}

      - name: Determine New Version
        id: create-version
        env:
          NEW_VERSION: ${{ steps.create-version.outputs.new_version }}
        run: |
          case ${{ github.event.inputs.release_type }} in
          major)
           version=$(echo "${{ steps.set-tag.outputs.latest_tag }}" | awk -F. '{printf "v%d.%d.%d\n", $1+1, 0, 0}')
           ;;
          minor)
           version=$(echo "${{ steps.set-tag.outputs.latest_tag }}" | awk -F. '{printf "v%d.%d.%d\n", $1, $2+1, 0}')
           ;;
          patch)
           version=$(echo "${{ steps.set-tag.outputs.latest_tag }}" | awk -F. '{printf "v%d.%d.%d\n", $1, $2, $3+1}')
           ;;
          *)
           echo "Invalid release type specified."
           exit 1
           ;;
          esac
          echo "v: "${version}
          echo "NEW_VERSION=${version}" >> $GITHUB_OUTPUT

      - name: Create Tag
        run: |
          git config user.email "${{ secrets.BOT_EMAIL }}"
          git config user.name "${{ secrets.BOT_NAME }}"
          git tag -a "${{ steps.create-version.outputs.new_version }}" -m "${{ github.event.inputs.tag_version_message }}"
          git push origin "${{ steps.create-version.outputs.new_version }}"
          echo ${GITHUB_OUTPUT}
          cat ${GITHUB_OUTPUT}

  test:
    needs: create-tag
    runs-on: ubuntu-latest
    steps:
      - name: print outputs
        shell: bash
        run: echo ${{ needs.create-version.outputs['new_version'] }}
      - name: Test me
        shell: bash
        env:
          VER: ${{ needs.create-version.outputs.new_version }}
        run: |
          MY_VERSION="${{ needs.create-version.outputs.new_version }}"
          echo "my version: ${{ needs.create-version.outputs.NEW_VERSION }}"
          echo "${{ env.NEW_VERSION }}"
          echo $MY_VERSION
          echo "ver: "${{ env.VER }}
      - name: Test me 2
        env:
          MY_TAG: ${{ needs.set-tag.outputs.latest_tag }}
        run: |
          echo "LATEST_TAG:$(echo '${{ needs.set-tag.outputs.latest_tag }}') and env:${{ env.MY_TAG }}"
          echo "t="${{ env.MY_TAG }}